---
#Creates the horizontal Pod Autoscalar to help in handling more load and create multiple pods if required to tackle the load
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: upg-loadme
  namespace: demo
spec:
  # Add hpa spec as per requirement
  # Refer: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#creating-the-autoscaler-declaratively
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upg-loadme
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 #Setting CPU utilization limit to 50% so new pod is created once the limit is reached.