#This is the statefulset redis server that uses persistent volume claims to persist data so that even after pods are restarted data stays.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
  namespace: demo
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: rafi-pv-storage
          # mountPath: /var/lib/redis
          persistentVolumeClaim:
            claimName: rafi-pvc
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
        volumeMounts:
        - name: rafi-pv-storage
          mountPath: "/var/lib/redis"
        envFrom:
        - configMapRef:
            name: redis

---
#Service to make the above statefulset accessible externally
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo
  labels:
    app: redis
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: redis
---